name: Quarkiverse Prepare Release

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  show_github:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'

  prepare-release:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true}}
    name: Prepare Release
    uses: quarkiverse/.github/.github/workflows/prepare-release.yml@main
    secrets: inherit
