name: Quarkiverse Prepare Release

on:
  workflow_dispatch:
    inputs:
      externalCall:
        description: 'To distinguish workflow_call from regular push'
        type: boolean
        required: false
        default: true
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-release:
    name: Prepare Release
    if: ${{ inputs.externalCall || github.event.pull_request.merged == true}}
    uses: quarkiverse/.github/.github/workflows/prepare-release.yml@main
    secrets: inherit
